# test-batch-speaker-guard.ps1 -- mock-based test for the 2026-07-02 audit fixes:
#  (1) turn-0 speaker misroute guard: an active undispatched PARALLEL workpack batch must be routed
#      to the claude planner path (Test-DriverBatchForcesClaudeSpeaker in driver/82-loop-turn-setup.ps1)
#      and Test-DirectCoderTask (driver/30-prompt-agent-state.ps1) must reject workpack-batch texts;
#  (2) tools/decompose-worker.ps1 must accept -DiffusionMode 'wide' and pass the wave-size knobs
#      (static source checks -- the worker launches codex, so no live run here).
# No live bridge required; exits 0 on success, 1 on any failure.
$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$script:failCount = 0

function Assert-True {
  param([bool]$Condition, [string]$Name)
  if ($Condition) { Write-Host ("PASS " + $Name) }
  else { $script:failCount++; Write-Host ("FAIL " + $Name) }
}

# ---------- 0) Parse-check the edited files ----------
$editedFiles = @(
  (Join-Path $repoRoot 'driver\82-loop-turn-setup.ps1'),
  (Join-Path $repoRoot 'driver\30-prompt-agent-state.ps1'),
  (Join-Path $repoRoot 'tools\decompose-worker.ps1')
)
foreach ($f in $editedFiles) {
  $tok = $null; $err = $null
  [void][System.Management.Automation.Language.Parser]::ParseFile($f, [ref]$tok, [ref]$err)
  Assert-True (@($err).Count -eq 0) ("parse clean: " + (Split-Path -Leaf $f))
}

# ---------- 1) Pure guard predicate: Test-DriverBatchForcesClaudeSpeaker ----------
# Dot-sourcing 82 only defines the function + assigns the loop scriptblock (never executed here).
. (Join-Path $repoRoot 'driver\82-loop-turn-setup.ps1')

$stBatch = [pscustomobject]@{ workpack_batch_active = $true; workpack_batch_mode = 'auto_parallel'; workpack_batch_dispatched = $false }
Assert-True ([bool](Test-DriverBatchForcesClaudeSpeaker -State $stBatch -TaskTurn 0)) 'guard: active undispatched auto_parallel batch at turn 0 -> forces claude'
Assert-True (-not (Test-DriverBatchForcesClaudeSpeaker -State $stBatch -TaskTurn 1)) 'guard: turn 1 -> no force (normal alternation)'

$stDispatched = [pscustomobject]@{ workpack_batch_active = $true; workpack_batch_mode = 'auto_parallel'; workpack_batch_dispatched = $true }
Assert-True (-not (Test-DriverBatchForcesClaudeSpeaker -State $stDispatched -TaskTurn 0)) 'guard: already-dispatched batch -> no force'

$stSerial = [pscustomobject]@{ workpack_batch_active = $true; workpack_batch_mode = 'serial'; workpack_batch_dispatched = $false }
Assert-True (-not (Test-DriverBatchForcesClaudeSpeaker -State $stSerial -TaskTurn 0)) 'guard: serial batch mode -> no force'

$stInactive = [pscustomobject]@{ workpack_batch_active = $false; workpack_batch_mode = 'auto_parallel'; workpack_batch_dispatched = $false }
Assert-True (-not (Test-DriverBatchForcesClaudeSpeaker -State $stInactive -TaskTurn 0)) 'guard: no active batch -> no force'

Assert-True (-not (Test-DriverBatchForcesClaudeSpeaker -State $null -TaskTurn 0)) 'guard: null state -> no force'
$stNoFields = [pscustomobject]@{ current_task = 'x' }
Assert-True (-not (Test-DriverBatchForcesClaudeSpeaker -State $stNoFields -TaskTurn 0)) 'guard: state without batch fields -> no force'

# ---------- 2) Speaker decision with stubbed Read-State ----------
# Stub Read-State exactly as the driver block consumes it, then evaluate the same sub-chain the
# driver uses at turn 0 for a normal-mode task with BOTH codex fast paths trying to fire.
function Read-State {
  return [pscustomobject]@{
    workpack_batch_active = $true
    workpack_batch_mode = 'auto_parallel'
    workpack_batch_dispatched = $false
    skip_planner = $true
  }
}

# Build sample task texts. Added code must stay ASCII, so the Russian batch-tag prefix
# 'Avtozadacha iz ' is composed from explicit Cyrillic code points (mirrors the live text
# generated by New-BacklogWorkpackBatchTaskText in lib/backlog-workpack.ps1).
$ruAvtozadachaIz = -join @([char]0x0410,[char]0x0432,[char]0x0442,[char]0x043E,[char]0x0437,[char]0x0430,[char]0x0434,[char]0x0430,[char]0x0447,[char]0x0430,[char]0x0020,[char]0x0438,[char]0x0437,[char]0x0020)
$ruSozday = -join @([char]0x0421,[char]0x043E,[char]0x0437,[char]0x0434,[char]0x0430,[char]0x0439)  # imperative 'create'
$nl = [Environment]::NewLine
$batchText = '[' + $ruAvtozadachaIz + 'workpack-batch] ' + $ruSozday + ' 2 tasks in one pass.' + $nl +
  'ITEM 1: backlog_id=aaa111' + $nl +
  'Files: app/src/main/java/Foo.kt' + $nl +
  'Task: ' + $ruSozday + ' app/src/main/java/Foo.kt' + $nl +
  '[[PARALLEL:wp1]]' + $nl + 'Files: app/src/main/java/Foo.kt' + $nl + '[[/PARALLEL:wp1]]' + $nl +
  'ITEM 2: backlog_id=bbb222' + $nl +
  'Files: app/src/main/java/Bar.kt' + $nl +
  '[[PARALLEL:wp2]]' + $nl + 'Files: app/src/main/java/Bar.kt' + $nl + '[[/PARALLEL:wp2]]' + $nl +
  'STATUS: CONTINUE'
$singleFileText = $ruSozday + ' tools/sample-single.ps1 with one small helper inside.'

# Stub the backlog target-file matcher (lib is not loaded in this mock harness): return a target
# for both samples so Test-DirectCoderTask's verdict is decided by the batch exclusion, not by an
# empty target.
function Get-BacklogTaskTargetFile {
  param([string]$Text)
  if ($Text -match 'app/src/main/java/Foo\.kt') { return 'app/src/main/java/Foo.kt' }
  if ($Text -match 'tools/sample-single\.ps1') { return 'tools/sample-single.ps1' }
  return ''
}

# driver/30 references $bridgeRoot at dot-source time (agent_pids path) -- point it at a temp dir.
$bridgeRoot = Join-Path $env:TEMP 'batch-speaker-guard-test'
if (-not (Test-Path -LiteralPath $bridgeRoot)) { New-Item -ItemType Directory -Force -Path $bridgeRoot | Out-Null }
. (Join-Path $repoRoot 'driver\30-prompt-agent-state.ps1')

$tt = 0; $mode = 'normal'; $task = $batchText; $skipPlanner = $true
$batchForcesClaude = $false
try { $batchForcesClaude = [bool](Test-DriverBatchForcesClaudeSpeaker -State (Read-State) -TaskTurn $tt) } catch {}
$speaker = if ($batchForcesClaude) { 'claude' }
           elseif ($skipPlanner -and $mode -eq 'normal' -and $tt -eq 0) { 'codex' }
           elseif ($tt -eq 0 -and $mode -eq 'normal' -and (Test-DirectCoderTask -TaskText $task)) { 'codex' }
           elseif ($tt -eq 0) { 'claude' }
           else { 'next-speaker' }
Assert-True ($speaker -eq 'claude') 'speaker decision: stubbed Read-State batch state routes turn 0 to claude despite both codex fast paths'

# Static ordering: in the real chain the guard branch must sit ABOVE both codex fast-path branches.
$src82 = Get-Content -Raw -LiteralPath (Join-Path $repoRoot 'driver\82-loop-turn-setup.ps1')
$iGuard  = $src82.IndexOf('elseif ($batchForcesClaude)')
$iSkip   = $src82.IndexOf('elseif ($skipPlanner -and $mode')
$iDirect = $src82.IndexOf('(Test-DirectCoderTask -TaskText $task)) { ''codex'' }')
Assert-True ($iGuard -ge 0 -and $iSkip -gt $iGuard -and $iDirect -gt $iGuard) 'static: guard branch precedes both codex fast-path branches in 82-loop-turn-setup.ps1'

# ---------- 3) Test-DirectCoderTask batch exclusion ----------
Assert-True (-not (Test-DirectCoderTask -TaskText $batchText)) 'Test-DirectCoderTask: false on workpack-batch task text'
Assert-True ([bool](Test-DirectCoderTask -TaskText $singleFileText)) 'Test-DirectCoderTask: true on plain single-file coder text'

$twoBlocksNoTag = 'Do work.' + $nl + '[[PARALLEL:wp1]]' + $nl + 'Files: app/src/main/java/Foo.kt' + $nl + '[[/PARALLEL:wp1]]' + $nl + '[[PARALLEL:wp2]]' + $nl + '[[/PARALLEL:wp2]]'
Assert-True (-not (Test-DirectCoderTask -TaskText $twoBlocksNoTag)) 'Test-DirectCoderTask: false on 2+ [[PARALLEL: blocks without the batch tag'

$oneMention = $ruSozday + ' tools/sample-single.ps1 and note: [[PARALLEL:*]] is mentioned once only.'
Assert-True ([bool](Test-DirectCoderTask -TaskText $oneMention)) 'Test-DirectCoderTask: single [[PARALLEL: mention (serial-batch shape) does NOT trigger the exclusion'

$serialTag = '[' + $ruAvtozadachaIz + 'protected-serial-workpack] header line'
Assert-True (-not ($serialTag -match '(?is)^\s*\[[^\]]*workpack-batch\]')) 'regex: protected-serial-workpack tag is NOT matched by the batch-tag rule'

# ---------- 4) decompose-worker.ps1 wide mode + wave params + transcript (static) ----------
$srcW = Get-Content -Raw -LiteralPath (Join-Path $repoRoot 'tools\decompose-worker.ps1')
Assert-True ($srcW.Contains("@('off','shadow','diffusion','wide')")) 'decompose-worker: mode validation accepts wide'
Assert-True ($srcW.Contains('-DiffusionMinIndependentAtoms $diffusionMinAtoms')) 'decompose-worker: passes -DiffusionMinIndependentAtoms to coordinator prompt builder'
Assert-True ($srcW.Contains('-DiffusionMaxWaveSize $diffusionMaxWave')) 'decompose-worker: passes -DiffusionMaxWaveSize to coordinator prompt builder'
Assert-True ($srcW.Contains('background-decompose.log')) 'decompose-worker: writes start/end transcript under the channel dir'
Assert-True ($srcW.Contains('diffusionMinIndependentAtoms') -and $srcW.Contains('diffusionMaxWaveSize')) 'decompose-worker: reads wave-size knobs from project-autopilot config'

# ---------- result ----------
if ($script:failCount -gt 0) {
  Write-Host ("RESULT: FAIL (" + $script:failCount + " assertion(s) failed)")
  exit 1
}
Write-Host 'RESULT: ALL PASS'
exit 0
